# -*- encoding: utf-8 -*-

=begin
#Conekta API

#Conekta sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@conekta.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "conekta/version"

Gem::Specification.new do |s|
  s.name        = "conekta"
  s.version     = Conekta::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Conekta"]
  s.email       = ["core@conekta.com"]
  s.homepage    = "https://www.conekta.com"
  s.summary     = "This library provides https://api.conekta.io operations"
  s.description = "Ruby library for https://api.conekta.io"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.6"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
