=begin
#Conekta API

#Conekta sdk

The version of the OpenAPI document: 2.1.0
Contact: engineering@conekta.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require_relative 'base_test'
require 'json'

# Unit tests for Conekta::BalancesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BalancesApi' do
  before do
    # run before each test
    Conekta.configure do |config|
      config.host = BaseTest.host
      config.access_token = 'key_xxxxxx'
      config.scheme = BaseTest.scheme
    end
    @api_instance = Conekta::BalancesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BalancesApi' do
    it 'should create an instance of BalancesApi' do
      expect(@api_instance).to be_instance_of(Conekta::BalancesApi)
    end
  end

  # unit tests for get_balance
  # Get a company&#39;s balance
  # Get a company&#39;s balance
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language Use for knowing which language to use
  # @return [BalanceResponse]
  describe 'get_balance test' do
    it 'should work' do
      response = @api_instance.get_balance({accept_language: 'es'})

      expect(response).to be_instance_of(Conekta::BalanceResponse)
      expect(response.available).to be_instance_of(Array)
    end
  end

end
