=begin
#Conekta API

#Conekta sdk

The version of the OpenAPI document: 2.2.0
Contact: engineering@conekta.com
Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Conekta::BalancesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BalancesApi' do
  before do
    # run before each test
    @api_instance = Conekta::BalancesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BalancesApi' do
    it 'should create an instance of BalancesApi' do
      expect(@api_instance).to be_instance_of(Conekta::BalancesApi)
    end
  end

  # unit tests for get_balance
  # Get a company&#39;s balance
  # Get a company&#39;s balance
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language Use for knowing which language to use
  # @return [BalanceResponse]
  describe 'get_balance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
