name: CI
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test (Ruby ${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6, 2.7, 3.0, 3.1, 3.2]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Bundle Install
        run: bundle install

      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v2
        with:
          version: 'latest'
          data-file: 'https://raw.githubusercontent.com/conekta/openapi/main/mocks/conekta_api.json'
          port: 3000

      - name: Test
        run: make ci-test
        env:
          BASE_PATH: http://localhost:3000
      - name: Build
        run: gem build conekta.gemspec
