name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version:  3.1
    - name: Lint
      run: bundle install
    - name: Build
      run: gem build conekta.gemspec

  test:
    name: Test (${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6, 2.7, '3.0', 3.1, 3.2]
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install Mockserver
      run: |
        npm install -g @mockoon/cli
        npx mockoon-cli start --data https://raw.githubusercontent.com/conekta/openapi/main/mocks/conekta_api.json --port 3000
    - name: test
      run: make ci-test
      env:
        BASE_PATH: http://localhost:3000

